"""
@file wimper.py
@description WIMPER (Section 125) calculation logic.
             WIMPER is a pre-tax cafeteria plan deduction that reduces
             the employee's taxable gross pay, generating payroll tax savings.
"""


def calculate_wimper_tax_savings(wimper: float, gross_pay: float) -> float:
    """
    Estimates the payroll tax savings generated by a given WIMPER amount.
    Savings come from reduced FICA taxes (Social Security + Medicare) on
    the pre-tax deduction amount.

    @param wimper: Section 125 pre-tax deduction amount
    @param gross_pay: Employee gross pay for the period
    @returns: Estimated employee payroll tax savings
    """
    # FICA rate: 6.2% Social Security + 1.45% Medicare = 7.65%
    FICA_RATE = 0.0765

    # Taxable gross after WIMPER deduction
    taxable_gross = max(0, gross_pay - wimper)

    # Tax on original gross vs reduced gross
    original_fica = gross_pay * FICA_RATE
    reduced_fica = taxable_gross * FICA_RATE

    return round(original_fica - reduced_fica, 2)


def calculate_employer_wimper_savings(wimper: float) -> float:
    """
    Calculates employer-side FICA savings from WIMPER.
    Employer also saves 7.65% FICA on the pre-tax amount.

    @param wimper: Section 125 pre-tax deduction amount
    @returns: Employer payroll tax savings
    """
    EMPLOYER_FICA_RATE = 0.0765
    return round(wimper * EMPLOYER_FICA_RATE, 2)
